export const ACTION_CHANGE_CHART_TYPE = 'ACTION_CHANGE_CHART_TYPE';
export const ACTION_ADD_BLOCK_TO_CHART = 'ACTION_ADD_BLOCK_TO_CHART';
export const ACTION_RECALC_SVG_PARAMS = 'ACTION_RECALC_SVG_PARAMS';
export const ACTION_REMOVE_BLOCK_FROM_CHART = 'ACTION_REMOVE_BLOCK_FROM_CHART';
export const ACTION_EDIT_BLOCK_PARAMS = 'ACTION_EDIT_BLOCK_PARAMS';
export const ACTION_CHANGE_FORM_STATE = 'ACTION_CHANGE_FORM_STATE';
